name : Hello world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: 
          echo "Hello this is ${{ vars.MY_NAME }}"
          echo "Hello this is ${{ secrets.dockerPassword }}"